---
title: "Baltimore Demographic Mapping"
author: "Shreya Vuttaluru"
date: '2022-09-21'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidycensus)
library(formattable)
library(htmlwidgets)
library(leaflet)
library(sf)
library(formattable)
library(dplyr)
library(tidyr)
library(janitor)
library(htmlwidgets)
```

## R Markdown

The code below was written for Professor Rob Well's Baltimore Reporting class at The University of Maryland. Data was not inputted into this Hithub portfolio because the project is still in the works. To see the resulting maps created below, click here https://profrobwells.github.io/Baltimore/rlining_and_demographics.html.

```{r}
## Aggregate Income Analysis + Map -- Shreya 
acs_2020_vars <- load_variables(year = 2020,
                      dataset = "acs5")

## pulling aggregate income for MD in 2020 and 2010
aggregate_income_2020 <- get_acs(
  geography = "tract", 
  state = "MD",
  variables = c(aggregate_income = "B19313_001"),
  year = 2020,
  geometry = TRUE) %>% 
  mutate(year=("2020")) %>%
  clean_names() %>%
  separate(name, into=c("tract","name","state"), sep=",") %>%
  mutate(
    state = str_trim(state,side="both"),
    name = str_trim(name,side="both")
      ) 

aggregate_income_2010 <- get_acs(
  geography = "tract", 
  state = "MD",
  variables = c(aggregate_income = "B19313_001"),
  year = 2010,
  geometry = TRUE) %>% 
  mutate(year=("2010")) %>%
  clean_names() %>%
  separate(name, into=c("tract","name","state"), sep=",") %>%
  mutate(
    state = str_trim(state,side="both"),
    name = str_trim(name,side="both")
      ) 

## filtering below for income in both 2010 and 2020
bmore_ag_income_2020 <- aggregate_income_2020 %>%
  filter(name == "Baltimore city") %>%
  rename(
    ag_income_2020 = estimate
  ) %>%
  as.data.frame() 

bmore_ag_income_2010 <- aggregate_income_2010 %>%
  filter(name == "Baltimore city") %>%
  rename(
    ag_income_2010 = estimate
  ) %>%
  as.data.frame()

### join both years together so 2010 and 2020 estimates are in the same df
bmore_ag_differences <- bmore_ag_income_2020 %>%
  left_join(bmore_ag_income_2010, by=c("geoid")) %>%
  dplyr::select(geoid, tract.x, state.x, ag_income_2020, geometry.x, ag_income_2010) %>%
  rename(
    tract = tract.x,
    state = state.x,
    geometry = geometry.x 
  ) %>%
  mutate(
    diff_ag_income = (ag_income_2020 - ag_income_2010)
  )

### incorporating community statistical areas into data 
#Baltimore has 56 neighborhoods as measured by Community Statistical Areas
csa <- rio::import("https://raw.githubusercontent.com/profrobwells/Baltimore/main/CTA_CSA_2010.csv") %>%
  rename(
    geoid = GEOID10
  ) %>%
  clean_names()

csa$geoid <- as.character(csa$geoid)

## wgs projection for mapping
wgs <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"

## rename columns for ease of joining
bmore_ag_differences_join <- bmore_ag_differences %>% 
  right_join(csa, by=c("geoid")) %>% 
  distinct() %>% 
  rename(neighborhood = csa2010,
  census_tract = name10) 

## making dataframe into spatial object for mapping
spatial_bmore_ag_differences <- bmore_ag_differences_join %>%
  st_as_sf(crs = wgs)

## palette 
ag_pal <- colorNumeric(
      palette = "inferno",
      domain = spatial_bmore_ag_differences$diff_ag_income
    )

## leaflet map here
ag_map <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = spatial_bmore_ag_differences,
              color = ~ag_pal(diff_ag_income),
              weight = 2.5,
              smoothFactor = 0.2,
              fillOpacity = 0.5,
              label = paste("Change is:",(scales::dollar(spatial_bmore_ag_differences$diff_ag_income)), "for",spatial_bmore_ag_differences$neighborhood)) %>% 
  addLegend(
    position = "bottomright",
    pal = ag_pal,
    values = spatial_bmore_ag_differences$diff_ag_income,
    title = "Aggregate Income Change<br>Per Census Tract <br> 2010 to 2020"
  )

ag_map

##saving widget!
saveWidget(ag_map, "aggregate_income_map.html")

```


Redlining Maps w/ Race and Per Capita Income  -- Shreya 
```{r}

### reading in redlining map shapefiles
redlining_maps <- st_read("Tracts_2020_HOLC/Tracts_2020_HOLC.shp") 

balt_redlining <- redlining_maps %>%
  clean_names() %>%
  filter(max_city == "Baltimore") %>%
  st_transform(crs = wgs)

d_regions <- balt_redlining %>%
  filter(first_holc == "D")


## pulling race data from ACS
race_2020 <- get_acs(
  geography = "tract", 
  state = "MD",
  variables = 
    c(total_population = "B03002_001",
      white_pop = "B03002_003",
      black_pop = "B03002_004",
      hisp_lat_pop = "B03002_012",
      asian_pop = "B03002_006"),
  year = 2020,
  geometry = TRUE,
  output = "wide"
  ) %>% 
  mutate(year=("2020")) %>%
  clean_names() %>%
  separate(name, into=c("tract","name","state"), sep=",") %>%
  mutate(
      state = str_trim(state,side="both"),
      name = str_trim(name,side="both")
  ) %>%
  filter(name == "Baltimore city")

balt_race_percentages <- race_2020 %>%
  mutate(
    percent_white = round((white_pop_e/total_population_e) * 100, 2),
    percent_black = round((black_pop_e/total_population_e) * 100, 2),
    percent_hisp_lat = round((hisp_lat_pop_e/total_population_e) * 100, 2),
    percent_asian = round((asian_pop_e/total_population_e) * 100, 2) 
    ) %>%
  select(geoid, tract, name, state, percent_white, percent_black, percent_hisp_lat, percent_asian, total_population_e) %>%
  rename(total_population = total_population_e)


## incorporating CSAs
### incorporating community statistical areas into data 
#Baltimore has 56 neighborhoods as measured by Community Statistical Areas
csa <- read_csv("balt_census_crosswalks_2020.csv") %>%
  rename(
    geoid = GEOID_Tract_2020
  ) %>%
  clean_names()

csa$geoid <- as.character(csa$geoid)

## joining race percentages to CSAs

balt_race_percentages_join <- balt_race_percentages %>% 
  right_join(csa, by=c("geoid")) %>% 
  distinct() %>% 
  rename(neighborhood = community_statistical_area_2020,
  census_tract = tract_2020) 

#palettes 
rlining_pal <- colorQuantile(
      palette = "YlGnBu",
      domain = baltcity_percap_income$diff_2020_2010,
      10,
      reverse = TRUE
    )

black_pal <- colorBin(
      palette = "YlGnBu",
      domain = balt_race_percentages_join$percent_black
    )

white_pal <- colorBin(
      palette = "YlGnBu",
      domain = balt_race_percentages_join$percent_white,
      5
    )

### this supposedly helps to bring things to the front?
  
## overlaying redlining shapefiles on top of leafMap (median household income)
rlining_and_demographics <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(group = "Per Capita Income",
              data = baltcity_percap_income,
              color = ~rlining_pal(diff_2020_2010),
              weight = 2.5,
              smoothFactor = 0.2,
              fillOpacity = 0.7,
              label = paste("Change is:",(scales::dollar(baltcity_percap_income$diff_2020_2010)), "for",balt_race_percentages_join$neighborhood)) %>% 
  addPolygons(group = "Black Population",
              data = balt_race_percentages_join,
              color = ~black_pal(percent_black),
              weight = 2.5,
              smoothFactor = 0.2,
              fillOpacity = 0.7,
              label = paste("Percent Black:",(balt_race_percentages_join$percent_black), "for",balt_race_percentages_join$neighborhood, "|", "Percap $ Change is:",(scales::dollar(baltcity_percap_income$diff_2020_2010)), "for",balt_race_percentages_join$neighborhood)) %>%
  addPolygons(group = "White Population",
              data = balt_race_percentages_join,
              color = ~white_pal(percent_white),
              weight = 2.5,
              smoothFactor = 0.2,
              fillOpacity = 0.7,
              label = paste("Percent White:",(balt_race_percentages_join$percent_white), "for",balt_race_percentages_join$neighborhood, "|", "Percap $ Change is:",(scales::dollar(baltcity_percap_income$diff_2020_2010)), "for",balt_race_percentages_join$neighborhood)) %>%
  ### needs to be polylines because otherwise hover gets messed up
  addPolylines(
    group = "Redlining Zones",
    data = d_regions,
    color = "Red",
    weight = 5,
    smoothFactor = 1,
    options = marker_options
  ) %>%
  addLegend(
    group = "White Population",
    position = "bottomright",
    pal = white_pal,
    values = balt_race_percentages_join$percent_white,
    title = "Percentage White in 2020"
  ) %>% 
  addLegend(
    group = "Per Capita Income",
    position = "bottomright",
    pal = rlining_pal,
    values = baltcity_percap_income$diff_2020_2010,
    title = "Per Capita Income Change<br>Per Census Tract <br> 2010 to 2020"
  ) %>% 
  addLegend(
    group = "Black Population",
    position = "bottomright",
    pal = black_pal,
    values = balt_race_percentages_join$percent_black,
    title = "Percentage Black in 2020"
  ) %>%
  ### controls layers for toggle
  addLayersControl(
    baseGroups = c("Per Capita Income", "Black Population", "White Population"),
    position = "topleft", 
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  ### extra Javascript so that redlining layers stay as a top layer
   onRender("
    function(el, x) {
      this.on('baselayerchange', function(e) {
        e.layer.bringToBack();
      })
    }
  ")
 
rlining_and_demographics 

saveWidget(rlining_and_demographics , "rlining_and_demographics.html")


```



