---
title: "acs_deciles_leaflet"
author: "Shreya Vuttaluru and Rachel Logan"
date: '2022-03-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r libraries, echo = FALSE, warning=FALSE, message=FALSE, results='hide', message=FALSE}

library(tidyverse)
library(tidycensus)
library(janitor)
library(leaflet)
library(dplyr)
library(googlesheets4)
library(sf)
library(leaflet.extras)

```


```{r load_data}
#every census tract AND every retailer sales
clean_dec_nation_geometries <- readRDS("../../../data/processed/analysis/make_leaflet_maps/dec_nation_geometries.rds")
clean_acs_nation_geometries <- readRDS("../../../data/processed/analysis/make_leaflet_maps/acs_nation_geometries.rds")

# Pull retailer locations and count nationally

retailers_acs <- readRDS("../../../data/processed/a_retailers_geospatial/03_join_retailers/all_geocoded_retailers.rds") %>% 
  select(geoid = acs_2019_tract_geoid, 
         state = retailer_state, 
         city = retailer_city) %>% 
  group_by(geoid) %>% 
  summarize(count = n()) %>% 
  ungroup()

# Load ACS Geometries

acs_geometries <- clean_acs_nation_geometries %>% 
  left_join(retailers_acs, by=c("geoid")) %>% 
  filter(!is.na(count)) %>% 
  filter(total_pop > 100) %>% 
  mutate(retailer_concentration = count/total_pop * 10000)

# Pull demographic info nationally: ACS
all_demographic_info_acs <- readRDS("../../../data/processed/a_retailers_geospatial/05_get_census_data/demographic_percents_2019_acs.rds")

# Join demographic tracts to retailers.
acs_tracts_w_retailers <- acs_geometries %>%
  left_join(retailers_acs) %>%
  left_join(all_demographic_info_acs) %>%
  rename(retailer_count = count)

  
state_list <- c('Maryland','District of Columbia','Virginia','Michigan','Connecticut','South Carolina','New York','Texas','Louisiana','Arizona','Kentucky')

state_list <- c(states_with_sales = c("Arizona", "Louisiana", "Michigan", "New York", "South Carolina", "Texas"))
```

```{r make_decile_table, echo = FALSE, warning=FALSE, message=FALSE, results='hide', message=FALSE}

## making deciles by retailer concentrations

 states_list <- c("Arizona", "Connecticut", "District of Columbia", "Kentucky", "Louisiana", "Michigan", "New York", "South Carolina", "Texas", "Virginia", "New Jersey")

 states_list <- states_list[1:11] 

## for when we make the original sheet-- otherwise, will remake a copy with new name
# gs4_auth()
#  
#  google_sheet_ids <- tibble()
#  
#  make_google_sheets <- function(state_name) {
#    sheet_id_value <<- gs4_create(name = paste0(state_name, "_demo_census_tracts")) 
#    temp <- tibble(
#      state = state_name, sheet_id = sheet_id_value
#    ) 
#    google_sheet_ids <<- google_sheet_ids %>%
#      bind_rows(temp) 
#    #id <<- gs4_find(order_by = "createdTime desc", n_max = 5)
#  }
# 
#  lapply(states_list, make_google_sheets)
#  
#  write_rds(google_sheet_ids, "google_sheet_ids.rds")
# 
# google_sheet_ids <- read_rds("google_sheet_ids.rds")



all_acs_interest_tracts_nation <<- tibble()

build_decile_tables <- function(state_name) {
       
  #state_name <- states_list[2] ## for testing
  all_acs_interest_tracts <- tibble()
  
  acs_table <- acs_tracts_w_retailers %>% 
    as_tibble() %>%
    filter(state == state_name) %>%
    mutate(retailer_concentration = (retailer_count / total_pop) * 10000) %>%
    mutate(ret_con_decile = ntile(retailer_concentration, 10),
           ret_count_decile = ntile(retailer_count, 10),
           income_decile = ntile(-median_household_income, 10),
           education_decile = ntile(pct_hs_or_below, 10),
           poverty_decile = ntile(pct_poverty, 10))  %>% 
           # total_sales_decile = ntile(total_sales, 10),
           # avg_sales_decile = ntile(average_sales_per_store, 10),
           # total_sales_decile = ntile(total_sales, 10), #fine bc decile of all 0 is basically random-- 
           # avg_sales_decile = ntile(average_sales_per_store, 10)
           #just don't use these in points math
    arrange(desc(retailer_concentration)) %>%
    filter(ret_con_decile == 10 & 
          ret_count_decile == 10) %>%
    mutate(points = income_decile +
                    education_decile + 
                    poverty_decile) %>%
    select(-geometry)
    
  # if (state_name %in% states_with_sales){
  #   acs_table <- acs_table %>%
  #     mutate(point = points+ avg_sales_decile)
  # }

  acs_table <- acs_table %>% 
    arrange(desc(points)) %>%
    head(10)
   
  assign(paste0(state_name, "_acs_decile_table"),acs_table,envir=.GlobalEnv) 

  these_interest_tracts <- acs_table %>% 
     select(geoid)
     
  all_acs_interest_tracts <- bind_rows(
     all_acs_interest_tracts, these_interest_tracts
   ) %>% 
     distinct()
   
  all_acs_interest_tracts_nation <<- bind_rows(
     all_acs_interest_tracts_nation, all_acs_interest_tracts
   )
  
    #  write_csv(dec_black_table,
    # paste0("../../../data/processed/08_leaflet_maps/",state_name,
    # "_black_decile_table.csv"))  write_csv(dec_hispanic_table,
    # paste0("../../../data/processed/08_leaflet_maps/", state_name,
    # "_hispanic_decile_table.csv"))
    #  write_csv(acs_table,
    # paste0("../../../analysis/make_leaflet_maps/decile_tables/", state_name,
    #  "_acs_decile_table.csv"))

    # state_sheet_id <<- google_sheet_ids %>%
    #   filter(state == state_name)      %>%
    #   select(sheet_id) %>%
    #   as_vector()
    #  # sheet_write(dec_black_table, ss=state_sheet_id, sheet="dec_black_table")
    #  # sheet_write(dec_hispanic_table, ss=state_sheet_id,
    #  # sheet="dec_hispanic_table")
    #  sheet_write(acs_table, ss=state_sheet_id,
    # sheet="acs_table")

   
} 

lapply(states_list, build_decile_tables) 
```



# pull geometries
```{r pull_geom, echo = FALSE, warning=FALSE, message=FALSE, results='hide', message=FALSE}

options(tigris_use_cache = TRUE)

get_geoms <- function(state) {
  geometries <- get_acs(state = state,
                            variables = "B19013_001",
                            geography = "tract",
                            year = 2019,
                            geometry = TRUE)
  
  write_rds(geometries, paste0("../../../../data/processed/a_retailers_geospatial/acs_geometries/", state, "_acs_geoms.rds"))
  
  assign(state, geometries, envir= .GlobalEnv)
  
}

lapply(states_list, get_geoms)

```

Extra McAllen, TX Analysis
```{r mcallen, echo = FALSE, warning=FALSE, message=FALSE, results='hide', message=FALSE}
# 
# mccallen_tx_acs <- acs_geometries_with_demo_data %>%
#   filter(county == "Hidalgo County",
#          state == "Texas") %>%
#   left_join(acs_retailers) %>%
#   filter(retailer_city == "MCALLEN") %>%
#   arrange(desc(total_sales)) %>%
#   select(retailer_name, geoid, tract, county, state, retailer_address, retailer_city, retailer_zipcode, total_sales, median_household_income, pct_hs_or_below, pct_poverty, retailer_concentration)
# 
# 
# write_csv(mccallen_tx_acs, "../mccallen_tx_acs.csv")

```

Binding Geometries
```{r bind_geom, echo = FALSE, warning=FALSE, message=FALSE, results='hide', message=FALSE}

all_acs_geoms <- bind_rows(
  lapply(
    list.files(
      "../../../data/processed/08_leaflet_maps/state_tract_acs_geoms/", 
      pattern = ".rds", 
      full.names = TRUE
    ), 
    readRDS
  )
) %>%
  clean_names() %>%
  select(-variable, -estimate, -moe)

```


# Making map for all retailers but with clustered concentrations
```{r echo = FALSE, warning=FALSE, message=FALSE, results='hide', message=FALSE}

### bind geoids created above to all retailers

acs_tract_sales_geo <- all_acs_geoms %>%
  inner_join(acs_tract_sales) 

these_polygons_acs <- all_acs_interest_tracts_nation %>%
  left_join(acs_tract_sales_geo) %>%
  st_as_sf()

these_polygons_acs <- these_polygons_acs %>% 
  mutate(tract_label = 
     case_when(
              total_sales == 0 ~ paste0(these_polygons_acs$name," : ",
                                "GEOID: ",these_polygons_acs$geoid," | ",
                               round(these_polygons_acs$pct_poverty,1),"% in poverty | ",
                               round(these_polygons_acs$pct_hs_or_below,1)," % with a high school degree or below | ",
                               "media income $",these_polygons_acs$median_household_income),
              
              TRUE            ~ paste0(these_polygons_acs$name," : ",
                               "GEOID: ",these_polygons_acs$geoid," | ",
                               "total sales: $",round(these_polygons_acs$average_sales_per_store,2), " | ",
                               round(these_polygons_acs$pct_poverty,1),"% in poverty | ",
                               round(these_polygons_acs$pct_hs_or_below,1)," % with a high school degree or below | ",
                               "media income $",these_polygons_acs$median_household_income)
     )
  )

acs_retailers <- readRDS("../../../data/processed/03_join_retailers/acs_retailers_w_demo.rds") %>% 
  select(state:total_sales, joint_latitude, joint_longitude)

acs_retailers <- acs_retailers %>%
  mutate(joint_longitude = as.numeric(joint_longitude),
         joint_latitude = as.numeric(joint_latitude),
         retailer_label = 
            case_when(
               total_sales == 0 ~ paste0(retailer_name, " at ",retailer_address, ", ", retailer_city),
               is.na(total_sales) ~ paste0(retailer_name, " at ",retailer_address, ", ", retailer_city),
               TRUE             ~ paste0(retailer_name, " at ",retailer_address, ", ",retailer_city," with $",round(total_sales,2), " total sales")
            )
         )
  

BluePointIcon <- makeIcon(
  iconUrl = "https://github.com/Howard-Center-Investigations/lottery-leaflet-maps/raw/main/marker-icon.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 0, iconAnchorY = 0 #,
  #shadowUrl = "https://github.com/Howard-Center-Investigations/lottery-leaflet-maps/raw/main/marker-shadow.png",
  #shadowWidth = 41, shadowHeight = 41,
  #shadowAnchorX =10, shadowAnchorY = 0
)

retailer_demo_map <- leaflet() %>% 
  addProviderTiles(providers$Stamen.TonerLite) %>% 
  addMarkers(data = acs_retailers,
             ~joint_longitude,
             ~joint_latitude,
             label = ~retailer_label,
             clusterOptions = markerClusterOptions(),
             icon = BluePointIcon
  ) %>%
  addPolygons(data = these_polygons_acs,
                color = "blue",
                weight = 0.5,
                group = "these_polygons_acs",
                smoothFactor = 0.2,
                fillOpacity = 0.25,
                label = ~tract_label) %>%
   addSearchFeatures(
    targetGroups  = "these_polygons_acs",
    options = searchFeaturesOptions(zoom = 10, openPopup = TRUE))
  

retailer_demo_map

```

```{r map.}
retailer_demo_map
```














